---
#######################################
# install and update pip
#######################################
- name: Update YUM cache
  yum:
    name: '*'
    state: latest

- name: install python-pip
  yum:
    name: python-docker
    state: present

#######################################
# start docker containers
#######################################
- name: Create vaultwarden container
  docker_container:
    name: vaultwarden
    restart_policy: always
    image: vaultwarden/server:{{ vaultwarden_version }}
    restart: true # restart container
    volumes:
      - "{{ vaultwarden_volume_path }}:/data"
    env:
      TZ: "Asia/Ho_Chi_Minh"
      # vaultwarden config
      WEBSOCKET_ENABLED: "true"
      INVITATIONS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      DOMAIN: "https://vaultwarden.duongdx.com"

      # signup
      SIGNUPS_ALLOWED: "false"
      SIGNUPS_DOMAINS_WHITELIST: gmail.com
      SIGNUPS_VERIFY_RESEND_TIME: "3600"
      SIGNUPS_VERIFY_RESEND_LIMIT: "6"

      # login rate
      LOGIN_RATELIMIT_MAX_BURST: "10"
      LOGIN_RATELIMIT_SECONDS: "60"

      # admin token for /admin panel
      ADMIN_TOKEN: "$$argon2id$$v=19$$m=65540,t=3,p=4$$DUsO9sEkw482mRpuPPOMqb8vYkGfnxvw7AoUpuY/uzg$$fDqMvc3R93974UJegaWt/1lY5lSeA6I2PVVkVz90fjQ"

      # SMTP setting for verify email
      SMTP_HOST: "{{ smtp_host }}"
      SMTP_FROM: "{{ smtp_from }}"
      SMTP_PORT: "{{ smtp_port}}"
      SMTP_SECURITY: "{{ smtp_security }}"
      SMTP_USERNAME: "{{ auth_username }}"
      SMTP_PASSWORD: "{{ auth_password }}"
    published_ports: "8000:80"
