- name: install nginx
  yum:
    name: nginx
    state: present

- name: enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: remove nginx default config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx

- name: make nginx ssl path
  file:
    path: "{{ nginx_ssl_path }}"
    state: directory

- name: create server key
  openssl_privatekey:
    path: "{{ nginx_ssl_certificate_key }}"
    size: 4096
    mode: 0600
    type: RSA
    state: present

- name: create server's certificate signing request
  openssl_csr:
    path: "{{ nginx_ssl_csr }}"
    privatekey_path: "{{ nginx_ssl_certificate_key }}"

- name: create server's certificate
  openssl_certificate:
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    path: "{{ nginx_ssl_certificate }}"
    privatekey_path: "{{ nginx_ssl_certificate_key }}"
    csr_path: "{{ nginx_ssl_csr }}"


- name: passing nginx config
  template:
    src: vaultwarden.duongdx.com.conf.j2
    dest: /etc/nginx/conf.d/vaultwarden.duongdx.com.conf
    mode: 0644
    owner: root
    group: root
  notify: restart nginx
