- name: install sqlite3
  yum:
    name: sqlite3
    state: present

- name: create backup folder
  file:
    path: /srv/backup
    state: directory
    mode: 0000
    owner: root
    group: root

- name: passing vaultwarden-backup.service
  copy:
    src: vaultwarden-backup.service
    dest: /etc/systemd/system/vaultwarden-backup.service
    owner: root
    group: root
    mode: 0644

- name: start vaultwarden-backup.service
  service:
    name: vaultwarden-backup
    state: started
    enable: true

- name: vaultwarden-backup.timer
  copy:
    src: vaultwarden-backup.timer
    dest: /etc/systemd/system/vaultwarden-backup.timer
    owner: root
    group: root
    mode: 0644

- name: start vaultwarden-backup.timer
  service:
    name: vaultwarden-backup.timer
    state: started
    enable: true
