---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: restart vaultwarden-backup.timer
  systemd:
    name: vaultwarden-backup.timer
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart vaultwarden-backup.service
  systemd:
    name: vaultwarden-backup
    state: restarted
    enabled: true
    daemon_reload: true