---
# defaults file for observer
prometheus_version: v2.45.3
grafana_version: "10.1.9"
alertmanager_version: v0.27.0
alertmanagers_endpoint: 192.168.56.88:9093
prometheus_endpoint: http://192.168.56.88:9090

telegraf_host:
  - host: "192.168.56.90:9273"
    team: devops
    active: "true"

  - host: "192.168.56.91:9273"
    team: sys-admin
    active: "true"

  - host: "192.168.56.92:9273"
    team: sys-admin
    active: "false"

  - host: "192.168.56.93:9273"
    team: sys-admin
    active: "false"

  - host: "192.168.56.94:9273"
    team: sys-admin
    active: "false"

  - host: "192.168.56.95:9273"
    team: sys-admin
    active: "false"

blackbox_exporter_hosts:
  - "192.168.56.90:9115"
  - "192.168.56.91:9115"

pushgateway_hosts:
  - "192.168.56.90:9091"
  - "192.168.56.91:9091"

program_host:
  - "192.168.56.1:8001"

mysqld_exporter_hosts:
  - "192.168.56.90:9104"